CREATE TABLE tutoringsessions (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  student_id INTEGER REFERENCES studentroster(id) ON DELETE CASCADE NOT NULL,
  lesson_date DATE,
  next_session_info VARCHAR(360)
);