CREATE TABLE studentroster (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  first_name VARCHAR(60) NOT NULL,
  last_name VARCHAR(60) NOT NULL,
  phone VARCHAR(60),
  email VARCHAR(60),
  misc_info VARCHAR(900)
);

CREATE TABLE tutoringsessions (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  student_id INTEGER REFERENCES studentroster(id) ON DELETE CASCADE NOT NULL,
  lesson_date DATE,
  next_session_info VARCHAR(360)
);

CREATE TABLE lessontopics (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  lesson_id INTEGER REFERENCES tutoringsessions(id) ON DELETE CASCADE NOT NULL,
  lesson_date DATE,
  student_id INTEGER REFERENCES studentroster(id) ON DELETE CASCADE NOT NULL,
  topic_name VARCHAR(60),
  topic_content VARCHAR(900)
);